services:
  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqlcontainer
    restart: unless-stopped
    volumes:
      - ./dbinit/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - database_data:/var/lib/mysql
    ports:
      - 3606:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prot"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database_data: